---
title: "EntertainmentApps"
author: "Nur Imam Masri"
date: "2023-06-01"
output: html_document
---

```{r}
# Import Library Visualization
library(tidyverse)
library(ggplot2)
library(dplyr) # untuk transformasi data
library(plotly) # untuk membuat plot menjadi interaktif
library(glue) # untuk custom informasi saat plot interaktif
library(scales) # untuk custom keterangan axis atau lainnya
library(tidyr) # untuk custom keterangan axis atau lainnya
library(stringr)# untuk melakuan kustom teks pada tooltip
library(wordcloud2)
library(readr)
```

```{r}
spotify <- read_csv("datasets/data.csv", show_col_types = FALSE)
spotify$artists <- str_replace_all(spotify$artists, c("\\[" = "", "\\]" = "", "'"=""))
glimpse(spotify)
```

```{r}
chr_cols <- c("artists", "name", "id", "release_date")
fct_cols <- c("explicit", "mode")
num_cols <- c("valence", "acousticness", "danceability", "energy", "instrumentalness", "liveness", "loudness", "speechiness", "tempo")
int_cols <- c("year", "duration_ms", "key", "popularity")

spotify_clean <- spotify %>% 
  mutate(across(all_of(fct_cols), as.factor)) %>%
  mutate(across(all_of(num_cols), as.numeric)) %>% 
  mutate(across(all_of(int_cols), as.integer)) %>% 
  mutate(release_date = ifelse(nchar(release_date) == 4, paste(release_date,"-01-01", sep=""), release_date)) %>% 
  mutate(release_date = as.Date(release_date)) %>% 
  arrange(spotify_clean$year)

spotify_clean
```

```{r}
spotify_genre <- read_csv("datasets/data_by_genres.csv", show_col_types = FALSE)
glimpse(spotify_genre)
```

```{r}
fct_cols <- c("mode", "genres")
num_cols <- c("valence", "acousticness", "danceability", "energy", "instrumentalness", "liveness", "loudness", "speechiness", "tempo")
int_cols <- c("duration_ms", "key", "popularity")

spotify_genre_clean <- spotify_genre %>% 
  mutate(across(all_of(fct_cols), as.factor)) %>%
  mutate(across(all_of(num_cols), as.numeric)) %>% 
  mutate(across(all_of(int_cols), as.integer))

spotify_genre_clean
```

```{r}
spotify_by_year <- spotify_clean %>% 
    group_by(year) %>%
    summarise(across(c(-artists, -duration_ms, -explicit, -mode, -name, -release_date, -tempo, -id, -loudness, -popularity), mean, na.rm = TRUE))

data_agg1 <- spotify_by_year %>% 
  select(-key) %>% 
  gather(key = "Variable", value = "Value", - year)

plot1 <- ggplot(data_agg1, aes(x = year, y = Value)) + 
  geom_line(aes(color = Variable))  + 
  scale_color_manual(values = c("red", "green", "orange", "purple", "blue", "black", "darkgreen")) + 
  guides(color = FALSE) + 
  labs(x = "Year", y = "Value", title = "Preference Music Taste in the Past Century on Spotify") + 
  scale_x_continuous(limits = c(1921, 2020), breaks = seq(1921, 2020, 10)) +
  theme_minimal()


ggplotly(plot1)
```
