---
title: "EntertainmentApps"
author: "Nur Imam Masri"
date: "2023-06-01"
output: html_document
---

```{r}
library(tidyverse)
library(plotly)
library(scales)
library(glue)
library(DT)
library(wordcloud2)
library(readr)
library(dplyr)
library(ggplot2)
```

```{r}
spotify <- read.csv("datasets/spotify/data.csv")
spotify$artists <- str_replace_all(spotify$artists, c("\\[" = "", "\\]" = "", "'"=""))
glimpse(spotify)
```

```{r}
chr_cols <- c("artists", "name", "id", "release_date")
fct_cols <- c("explicit", "mode")
num_cols <- c("valence", "acousticness", "danceability", "energy", "instrumentalness", "liveness", "loudness", "speechiness", "tempo")
int_cols <- c("year", "duration_ms", "key", "popularity")

spotify_clean <- spotify %>% 
  mutate(across(all_of(fct_cols), as.factor)) %>%
  mutate(across(all_of(num_cols), as.numeric)) %>% 
  mutate(across(all_of(int_cols), as.integer)) %>% 
  mutate(release_date = ifelse(nchar(release_date) == 4, paste(release_date,"-01-01", sep=""), release_date)) %>% 
  mutate(release_date = as.Date(release_date)) %>% 
  arrange(spotify$year)

spotify_clean
```

```{r}
spotify_genre <- read.csv("datasets/spotify/data_by_genres.csv")
glimpse(spotify_genre)
```

```{r}
fct_cols <- c("mode", "genres")
num_cols <- c("valence", "acousticness", "danceability", "energy", "instrumentalness", "liveness", "loudness", "speechiness", "tempo")
int_cols <- c("duration_ms", "key", "popularity")

spotify_genre_clean <- spotify_genre %>% 
  mutate(across(all_of(fct_cols), as.factor)) %>%
  mutate(across(all_of(num_cols), as.numeric)) %>% 
  mutate(across(all_of(int_cols), as.integer))

spotify_genre_clean
```

```{r}
cr <- c("valence", "acousticness", "danceability", "energy", "instrumentalness", "liveness", "speechiness")
data_agg1 <- spotify_clean %>% 
  pivot_longer(cols = all_of(cr),
               names_to = "Variable",
               values_to = "Value") %>%
  group_by(year, Variable) %>% 
  summarize(Value = mean(Value))

data_agg1
```

```{r}
plot_time <- ggplot(data_year, aes(x = year, y = value)) +
  geom_line(aes(color = variable)) +
  scale_color_manual(name = "Taste", values = c("acousticness" = "red", "energy" = "green", "instrumentalness" = "orange", "liveness" = "purple")) +
  labs(x = "Year", y = "Value", title = "Music Taste in the Past Century") +
  scale_x_continuous(limits = c(1920, 2020),
                     breaks = seq(1920, 2020, 20)) +
  theme_minimal()

ggplotly(plot_time)
```

```{r}
spotify_year <- read_csv("datasets/spotify/data_by_year.csv", show_col_types = FALSE)
head(spotify_year)
```

```{r}
data_year <- spotify_year %>% 
  select(year, acousticness, energy, instrumentalness, liveness) %>% 
  gather(key = "variable", value = "value", -year)
data_year
```

```{r}
plot_time <- ggplot(data_year, aes(x = year, y = value)) + 
  geom_line(aes(color = variable)) + 
  scale_color_manual(values = c("red", "green", "orange", "purple")) + 
  guides(color = "none") + 
  labs(x = "Year", y = "Value", title = "Music Taste in the Past Century") + 
  scale_x_continuous(limits = c(1920, 2020), breaks = seq(1920, 2020, 20)) +
  theme_minimal()

ggplotly(plot_time)
```

```{r}
spotify_by_genre <- spotify_genre %>%
  group_by(genres) %>%
  summarise(mean_popularity = round(mean(popularity), 2)) %>%
  ungroup()%>% 
  arrange(desc(mean_popularity)) %>% 
  head(300)

wordcloud2(spotify_by_genre, color = "random-dark", size=0.3, backgroundColor = "white")
```

```{r}
spotify_genre %>%
  head(20) %>% 
  ggplot(aes(x = reorder(genres, -counts), y = counts)) + 
    geom_col(fill = 'royalblue4') +
    geom_text(aes(label = round(counts, 1)), vjust = 1.5, color = "white", size = 3.8) +
    scale_y_continuous(expand = c(0, 0)) +
    labs(title = "What is your favourite animal?",
         subtitle = "Percent of respondents") +
    theme(
      panel.background = element_rect(fill = NA),
      panel.grid.major = element_blank(),
      axis.ticks = element_blank(),
      axis.title = element_blank(),
      axis.text.x = element_text(size = 10, margin = margin(5, 0, 0, 0), angle = 90, hjust = 1),
      axis.text.y = element_blank()
    )
```

```{r}
data_agg2 <- spotify_clean %>%
  filter(year == 2020) %>%
  select(name, popularity, artists) %>%
  arrange(desc(popularity)) %>%
  mutate(text = glue("popularity: {popularity}
                      artists: {artists}")) %>%
  head(15)

plot_rank <- ggplot(data_agg2,
                    aes(x = popularity, y = reorder(name, popularity),
                        text = text)) +
  geom_col(aes(fill = popularity)) +
  scale_y_discrete(labels = wrap_format(30)) +
  scale_x_continuous(limits = c(0, 100), breaks = seq(0, 100, 10)) +
  scale_fill_gradient(low = "light blue", high = "dark blue") +
  labs(x = "Popularity (0-100)", y = NULL,
       title = glue("Top 15 Popular Songs")) +
  theme_minimal()

ggplotly(plot_rank, tooltip = "text")
```

```{r}
data_agg_4 <- spotify_clean %>%
  filter(year == 2020) %>%
  arrange(desc(popularity)) %>%
  head(1000)
data_agg_4
```

```{r}
plot_dist <- 
  ggplot(data_agg_4, mapping=aes(x = energy, y = loudness)) +
  geom_jitter(aes(col = as.factor(explicit),
                  text = glue("{str_to_upper(explicit)}
                              Title: {name}
                              Artists: {artists}
                              Popularity: {popularity}"))) +
  labs(x = "energy", y = "loudness",
       title = glue("Distribution of Songs")) +
  guides(color = "none") +
  theme_minimal()

ggplotly(plot_dist, tooltip = "text")
```
